/**
 * Resumo persistence — the saved study summary for a subject scope.
 *
 * One row per `(student, course, module)` (module NULL = whole course). The
 * generation pipeline lives in `summary.ts`; this module only reads/writes the
 * `study_summary` table so a Resumo survives reloads and can be regenerated by
 * upserting the same scope.
 */
import { query } from "./db.js";
import { getStudentId } from "./store.js";
import type { StudySummary } from "./types.js";

export interface NewStudySummary {
  courseId: number;
  moduleId: number | null;
  subjectLabel: string;
  content: string;
  model: string | null;
  promptHash: string | null;
  itemCount: number;
}

interface SummaryRow {
  id: string;
  course_id: string;
  module_id: string | null;
  subject_label: string;
  content: string;
  model: string | null;
  item_count: number;
  char_count: number;
  created_at: Date;
  updated_at: Date;
}

function toSummary(row: SummaryRow): StudySummary {
  return {
    id: Number(row.id),
    courseId: Number(row.course_id),
    moduleId: row.module_id != null ? Number(row.module_id) : null,
    subjectLabel: row.subject_label,
    content: row.content,
    model: row.model,
    itemCount: row.item_count,
    charCount: row.char_count,
    createdAt: row.created_at.toISOString(),
    updatedAt: row.updated_at.toISOString(),
  };
}

/** The saved Resumo for a scope, or null when none was generated yet. */
export async function getStudySummary(
  courseId: number,
  moduleId: number | null,
): Promise<StudySummary | null> {
  const studentId = await getStudentId();
  const rows = await query<SummaryRow>(
    `SELECT * FROM study_summary
     WHERE student_id = $1 AND course_id = $2 AND COALESCE(module_id, 0) = COALESCE($3, 0)`,
    [studentId, courseId, moduleId],
  );
  return rows[0] ? toSummary(rows[0]) : null;
}

/** Create or replace the saved Resumo for a scope; returns the fresh row. */
export async function saveStudySummary(input: NewStudySummary): Promise<StudySummary> {
  const studentId = await getStudentId();
  await query(
    `INSERT INTO study_summary(
       student_id, course_id, module_id, subject_label, content, model, prompt_hash, item_count, char_count, updated_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9, now())
     ON CONFLICT (student_id, course_id, COALESCE(module_id, 0)) DO UPDATE SET
       subject_label = EXCLUDED.subject_label,
       content       = EXCLUDED.content,
       model         = EXCLUDED.model,
       prompt_hash   = EXCLUDED.prompt_hash,
       item_count    = EXCLUDED.item_count,
       char_count    = EXCLUDED.char_count,
       updated_at    = now()`,
    [
      studentId,
      input.courseId,
      input.moduleId,
      input.subjectLabel,
      input.content,
      input.model,
      input.promptHash,
      input.itemCount,
      input.content.length,
    ],
  );
  const saved = await getStudySummary(input.courseId, input.moduleId);
  if (!saved) throw new Error("falha ao salvar o resumo");
  return saved;
}
