/**
 * Resumo persistence — the saved study summary for a subject scope.
 *
 * One row per `(student, course, module)` (module NULL = whole course). The
 * generation pipeline lives in `summary.ts`; this module only reads/writes the
 * `study_summary` table so a Resumo survives reloads and can be regenerated by
 * upserting the same scope.
 */
import { query } from "./db.js";
import { getStudentId } from "./store.js";
import type { StudySummary } from "./types.js";

export interface NewStudySummary {
  courseId: number;
  moduleId: number | null;
  examId?: number | null;
  subjectLabel: string;
  content: string;
  model: string | null;
  promptHash: string | null;
  itemCount: number;
}

interface SummaryRow {
  id: string;
  course_id: string;
  module_id: string | null;
  exam_id: string | null;
  subject_label: string;
  content: string;
  model: string | null;
  item_count: number;
  char_count: number;
  created_at: Date;
  updated_at: Date;
}

function toSummary(row: SummaryRow): StudySummary {
  return {
    id: Number(row.id),
    courseId: Number(row.course_id),
    moduleId: row.module_id != null ? Number(row.module_id) : null,
    examId: row.exam_id != null ? Number(row.exam_id) : null,
    subjectLabel: row.subject_label,
    content: row.content,
    model: row.model,
    itemCount: row.item_count,
    charCount: row.char_count,
    createdAt: row.created_at.toISOString(),
    updatedAt: row.updated_at.toISOString(),
  };
}

/** The saved Resumo for a scope, or null when none was generated yet. */
export async function getStudySummary(
  courseId: number,
  moduleId: number | null,
  examId: number | null = null,
): Promise<StudySummary | null> {
  const studentId = await getStudentId();
  const rows = await query<SummaryRow>(
    `SELECT * FROM study_summary
     WHERE student_id = $1 AND course_id = $2
       AND module_id IS NOT DISTINCT FROM $3::bigint
       AND exam_id IS NOT DISTINCT FROM $4::bigint`,
    [studentId, courseId, moduleId, examId],
  );
  return rows[0] ? toSummary(rows[0]) : null;
}

/** Create or replace the saved Resumo for a scope; returns the fresh row. */
export async function saveStudySummary(input: NewStudySummary): Promise<StudySummary> {
  const studentId = await getStudentId();
  const examId = input.examId ?? null;
  const params = [
    studentId,
    input.courseId,
    input.moduleId,
    examId,
    input.subjectLabel,
    input.content,
    input.model,
    input.promptHash,
    input.itemCount,
    input.content.length,
  ];
  // Manual upsert: the scope key has two nullable columns, so matching on the
  // expression index is avoided in favour of `IS NOT DISTINCT FROM`.
  const updated = await query<SummaryRow>(
    `UPDATE study_summary SET
       subject_label = $5, content = $6, model = $7, prompt_hash = $8,
       item_count = $9, char_count = $10, updated_at = now()
     WHERE student_id = $1 AND course_id = $2
       AND module_id IS NOT DISTINCT FROM $3::bigint
       AND exam_id IS NOT DISTINCT FROM $4::bigint
     RETURNING *`,
    params,
  );
  if (updated[0]) return toSummary(updated[0]);

  const inserted = await query<SummaryRow>(
    `INSERT INTO study_summary(
       student_id, course_id, module_id, exam_id, subject_label, content, model, prompt_hash, item_count, char_count, updated_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10, now())
     RETURNING *`,
    params,
  );
  return toSummary(inserted[0]);
}
