// One-command onboarding: `npm run setup`
// Installs deps + browser, collects credentials, writes env files, starts
// Postgres (Docker) + migrates, then can run the first scrape and start the app.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  ROOT,
  PORTAL_ENV,
  SERVER_ENV,
  PROFILE_JSON,
  c,
  log,
  ok,
  warn,
  bad,
  step,
  run,
  ask,
  askHidden,
  confirm,
  commandExists,
  dockerCompose,
  ensureEnvLine,
  envLine,
  readEnvFile,
  writeWithBackup,
  DATABASE_URL_DEFAULT,
} from "./shared.mjs";

log(`
  ${c.bold("lxp-toolkit · setup")}
  ${c.dim("UniFOA / Grupoa LXP scraper + LXP Toolkit app")}
`);

// 1. Node version
const major = Number(process.versions.node.split(".")[0]);
if (major < 22) {
  bad(`Node.js 22+ is required (found v${process.versions.node}).`);
  log("  Install it from https://nodejs.org, then run `npm run setup` again.");
  process.exit(1);
}

// 2. Dependencies
step("Installing dependencies");
const install = await run("npm", ["install"]);
if (install.code !== 0) {
  bad("npm install failed — see the output above.");
  process.exit(1);
}
ok("Dependencies installed.");

// 3. Playwright Chromium
step("Installing the Chromium browser");
const pw = await run("npx", ["playwright", "install", "chromium"]);
if (pw.code !== 0) {
  bad("Playwright install failed — see the output above.");
  process.exit(1);
}
// On bare Linux the browser binary alone is not enough: it needs shared
// libraries (libnss3, libatk, …). Install them only when we can do so without
// an interactive sudo prompt; otherwise point the user at the one-line fix.
if (process.platform === "linux") {
  const isRoot = typeof process.getuid === "function" && process.getuid() === 0;
  const canSudo = !isRoot && (await commandExists("sudo", ["-n", "true"]));
  if (isRoot || canSudo) {
    const deps = await run("npx", ["playwright", "install-deps", "chromium"], { tee: true });
    if (deps.code !== 0) {
      warn(
        "Could not install Chromium's system libraries automatically.\n" +
          "    If the browser fails to launch later, run: sudo npx playwright install-deps chromium",
      );
    }
  } else {
    warn(
      "Skipping Chromium's system libraries (needs root).\n" +
        "    If the browser fails to launch later, run: sudo npx playwright install-deps chromium",
    );
  }
}
ok("Chromium ready.");

// 4. Credentials
step("Your credentials");
log(c.dim("  Stored only in local, gitignored .env files — never committed."));
const ra = await ask("  Portal username (your RA): ");
if (!ra) {
  bad("Your RA is required.");
  process.exit(1);
}
const password = await askHidden("  Portal password: ");
if (!password) {
  bad("Your password is required.");
  process.exit(1);
}
const openai = await askHidden("  OpenAI API key (optional, press Enter to skip): ");
if (openai && !openai.startsWith("sk-")) {
  bad("That doesn't look like an OpenAI key (it should start with sk-).");
  process.exit(1);
}
if (!openai) {
  warn("Skipping the OpenAI key — scraping works, AI generation is disabled until you add one.");
}

// 5. AI profile (optional)
step("AI profile (optional — press Enter to skip)");
log(c.dim("  Used to sign the answers the AI drafts for you."));
const nome = await ask("  Full name: ");
const matricula = await ask("  Matrícula: ");

// 6. Write config
step("Writing configuration");
async function maybeWrite(file, content, label) {
  if (existsSync(file)) {
    const over = await confirm(`  ${label} already exists. Overwrite? (a .bak backup is kept)`, false);
    if (!over) {
      warn(`kept the existing ${label}`);
      return;
    }
  }
  writeWithBackup(file, content);
  ok(`wrote ${label}`);
}

const portalEnv = [
  "# Grupoa LXP scraper — generated by `npm run setup`",
  envLine("LXP_LOGIN_URL", "https://unifoa.lyceum.com.br/aluno/#/login"),
  envLine("LXP_USERNAME", ra),
  envLine("LXP_PASSWORD", password),
  envLine("LXP_URL", "https://unifoa2.grupoa.education/plataforma/"),
  envLine("API_BASE", "https://api.plataforma.grupoa.education"),
  envLine("TZ", "America/Sao_Paulo"),
  envLine("LOG_LEVEL", "info"),
  envLine("PLAYWRIGHT_NO_SANDBOX", "false"),
  "# HEADFUL=true   # uncomment if the portal asks for a reCAPTCHA",
  envLine("OUT_DIR", "scraped"),
  "",
].join("\n");

// Keep an existing key when the user chose to skip the prompt this time.
const existingServer = readEnvFile(SERVER_ENV) ?? {};
const openaiValue = openai || existingServer.OPENAI_API_KEY || "";
const serverEnv = [
  "# LXP Toolkit backend — generated by `npm run setup`",
  openaiValue ? envLine("OPENAI_API_KEY", openaiValue) : "# OPENAI_API_KEY=sk-...   # optional — needed for AI generation",
  envLine("DATA_DIR", "../../scraped"),
  envLine("PORT", "4174"),
  envLine("DATABASE_URL", DATABASE_URL_DEFAULT),
  "",
].join("\n");

await maybeWrite(PORTAL_ENV, portalEnv, "packages/portal/.env");
await maybeWrite(SERVER_ENV, serverEnv, "apps/server/.env");

// Existing installs may predate the database; make sure the URL is present.
if (ensureEnvLine(SERVER_ENV, "DATABASE_URL", DATABASE_URL_DEFAULT)) {
  ok("added DATABASE_URL to apps/server/.env");
}

if (nome || matricula) {
  mkdirSync(path.dirname(PROFILE_JSON), { recursive: true });
  writeFileSync(PROFILE_JSON, JSON.stringify({ nome, matricula }, null, 2), "utf8");
  ok("wrote apps/server/config/profile.json");
}

// 6b. Database (required)
step("Starting the database (Postgres)");
let dbReady = false;
const dockerCli = await commandExists("docker", ["--version"]);
const dockerDaemon = dockerCli && (await commandExists("docker", ["info"]));
if (!dockerCli) {
  warn(
    "Docker not found. Install it (Docker Desktop, or Docker Engine + the Compose v2 plugin),\n" +
      "    then run: npm run db:up && npm run db:migrate",
  );
} else if (!dockerDaemon) {
  warn(
    "Docker is installed but the daemon isn't responding. Start Docker Desktop (or the docker service),\n" +
      "    then run: npm run db:up && npm run db:migrate",
  );
} else {
  const up = await dockerCompose(["up", "-d", "db"], { tee: true });
  if (up.code === 0) {
    let ready = false;
    for (let i = 0; i < 30 && !ready; i++) {
      const probe = await dockerCompose(["exec", "-T", "db", "pg_isready", "-U", "lxp", "-d", "lxp"], {
        capture: true,
      });
      if (probe.code === 0) ready = true;
      else await new Promise((r) => setTimeout(r, 1000));
    }
    if (ready) {
      ok("Postgres is up.");
      const mig = await run("npm", ["run", "db:migrate"], { tee: true });
      if (mig.code === 0) {
        ok("Schema migrated.");
        dbReady = true;
      } else {
        warn("Migration failed — run `npm run db:migrate` after fixing the error.");
      }
    } else {
      warn("Postgres did not become ready in time — run `npm run db:migrate` once it is up.");
    }
  } else {
    warn("Could not start Postgres with `docker compose up -d db`.");
  }
}

// 7. PII commit guard
step("Enabling the personal-data commit guard");
const hooks = await run("git", ["config", "core.hooksPath", ".githooks"]);
if (hooks.code === 0) ok("git hooks enabled.");
else warn("could not enable git hooks (not a git repository?) — skipping.");

// 8. First scrape
step("First scrape");
let synced = false;
const doScrape = await confirm("  Scrape your portal content now?", true);
if (doScrape) {
  let res = await run("npm", ["run", "dump"], { tee: true });
  if (res.code !== 0 && /reCAPTCHA|CaptchaRequiredError/i.test(res.output)) {
    warn("The portal asked for a reCAPTCHA.");
    const retry = await confirm("  Retry with a visible browser so you can solve it?", true);
    if (retry) res = await run("npm", ["run", "dump"], { tee: true, env: { HEADFUL: "true" } });
  }
  if (res.code === 0) {
    ok("Content scraped.");
    if (dbReady) {
      const idx = await run("npm", ["run", "index:web"], { tee: true });
      if (idx.code !== 0) warn("Index failed — retry with `npm run index:web`.");
      else synced = true;
    } else {
      warn(
        "Skipping the index: the database isn't ready. Run `npm run db:up && npm run db:migrate && npm run index:web`.",
      );
    }
  } else {
    warn("The scrape did not finish — retry later with `npm run dump`.");
  }
} else {
  log(c.dim("  skipped — run `npm run dump` whenever you're ready."));
}

// 9. Start the app
step("All set");
if (!dbReady) {
  warn(
    "The database isn't ready, so the app can't start yet. Fix Docker, then run:\n" +
      "    npm run db:up && npm run db:migrate && npm run web",
  );
} else {
  const start = await confirm("  Start the app now (http://localhost:4174)?", true);
  if (start) {
    if (!synced) {
      warn(
        "No fresh scrape was indexed — the app will show whatever content already exists.\n" +
          "    Run `npm run sync` (or the app's Atualizar button) when you want fresh data.",
      );
    }
    log(c.dim("\n  Starting… press Ctrl+C to stop.\n"));
    // Setup already handled (or explicitly skipped) the refresh, so disable
    // `preweb`'s automatic `sync` to avoid a surprise second scrape.
    await run("npm", ["run", "web"], { env: { SKIP_SYNC: "1" } });
  } else {
    log(`  Start it later with: ${c.bold("npm run web")}`);
  }
}
log(`  Health check anytime: ${c.bold("npm run doctor")}\n`);
