// One-command onboarding: `npm run setup`
// Installs deps + browser, collects credentials, writes env files, and can run
// the first scrape and start the app.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  ROOT,
  PORTAL_ENV,
  SERVER_ENV,
  PROFILE_JSON,
  c,
  log,
  ok,
  warn,
  bad,
  step,
  run,
  ask,
  askHidden,
  confirm,
  envLine,
  writeWithBackup,
} from "./shared.mjs";

log(`
  ${c.bold("lxp-toolkit · setup")}
  ${c.dim("UniFOA / Grupoa LXP scraper + Pauta app")}
`);

// 1. Node version
const major = Number(process.versions.node.split(".")[0]);
if (major < 22) {
  bad(`Node.js 22+ is required (found v${process.versions.node}).`);
  log("  Install it from https://nodejs.org, then run `npm run setup` again.");
  process.exit(1);
}

// 2. Dependencies
step("Installing dependencies");
const install = await run("npm", ["install"]);
if (install.code !== 0) {
  bad("npm install failed — see the output above.");
  process.exit(1);
}
ok("Dependencies installed.");

// 3. Playwright Chromium
step("Installing the Chromium browser");
const pw = await run("npx", ["playwright", "install", "chromium"]);
if (pw.code !== 0) {
  bad("Playwright install failed — see the output above.");
  process.exit(1);
}
ok("Chromium ready.");

// 4. Credentials
step("Your credentials");
log(c.dim("  Stored only in local, gitignored .env files — never committed."));
const ra = await ask("  Portal username (your RA): ");
if (!ra) {
  bad("Your RA is required.");
  process.exit(1);
}
const password = await askHidden("  Portal password: ");
if (!password) {
  bad("Your password is required.");
  process.exit(1);
}
const openai = await askHidden("  OpenAI API key (sk-...): ");
if (!openai.startsWith("sk-")) {
  bad("That doesn't look like an OpenAI key (it should start with sk-).");
  process.exit(1);
}

// 5. AI profile (optional)
step("AI profile (optional — press Enter to skip)");
log(c.dim("  Used to sign the answers the AI drafts for you."));
const nome = await ask("  Full name: ");
const matricula = await ask("  Matrícula: ", { defaultValue: ra });

// 6. Write config
step("Writing configuration");
async function maybeWrite(file, content, label) {
  if (existsSync(file)) {
    const over = await confirm(`  ${label} already exists. Overwrite? (a .bak backup is kept)`, false);
    if (!over) {
      warn(`kept the existing ${label}`);
      return;
    }
  }
  writeWithBackup(file, content);
  ok(`wrote ${label}`);
}

const portalEnv = [
  "# Grupoa LXP scraper — generated by `npm run setup`",
  envLine("LXP_LOGIN_URL", "https://unifoa.lyceum.com.br/aluno/#/login"),
  envLine("LXP_USERNAME", ra),
  envLine("LXP_PASSWORD", password),
  envLine("LXP_URL", "https://unifoa2.grupoa.education/plataforma/"),
  envLine("API_BASE", "https://api.plataforma.grupoa.education"),
  envLine("TZ", "America/Sao_Paulo"),
  envLine("LOG_LEVEL", "info"),
  envLine("PLAYWRIGHT_NO_SANDBOX", "false"),
  "# HEADFUL=true   # uncomment if the portal asks for a reCAPTCHA",
  envLine("OUT_DIR", "scraped"),
  "",
].join("\n");

const serverEnv = [
  "# Pauta backend — generated by `npm run setup`",
  envLine("OPENAI_API_KEY", openai),
  envLine("DATA_DIR", "../../scraped"),
  envLine("PORT", "4174"),
  "",
].join("\n");

await maybeWrite(PORTAL_ENV, portalEnv, "packages/portal/.env");
await maybeWrite(SERVER_ENV, serverEnv, "apps/server/.env");

if (nome || matricula) {
  mkdirSync(path.dirname(PROFILE_JSON), { recursive: true });
  writeFileSync(PROFILE_JSON, JSON.stringify({ nome, matricula }, null, 2), "utf8");
  ok("wrote apps/server/config/profile.json");
}

// 7. PII commit guard
step("Enabling the personal-data commit guard");
const hooks = await run("git", ["config", "core.hooksPath", ".githooks"]);
if (hooks.code === 0) ok("git hooks enabled.");
else warn("could not enable git hooks (not a git repository?) — skipping.");

// 8. First scrape
step("First scrape");
const doScrape = await confirm("  Scrape your portal content now?", true);
if (doScrape) {
  let res = await run("npm", ["run", "dump"], { tee: true });
  if (res.code !== 0 && /reCAPTCHA|CaptchaRequiredError/i.test(res.output)) {
    warn("The portal asked for a reCAPTCHA.");
    const retry = await confirm("  Retry with a visible browser so you can solve it?", true);
    if (retry) res = await run("npm", ["run", "dump"], { tee: true, env: { HEADFUL: "true" } });
  }
  if (res.code === 0) {
    ok("Content scraped.");
    await run("npm", ["run", "index:web"], { tee: true });
  } else {
    warn("The scrape did not finish — retry later with `npm run dump`.");
  }
} else {
  log(c.dim("  skipped — run `npm run dump` whenever you're ready."));
}

// 9. Start the app
step("All set");
const start = await confirm("  Start the app now (http://localhost:4174)?", true);
if (start) {
  log(c.dim("\n  Starting… press Ctrl+C to stop.\n"));
  await run("npm", ["run", "web"]);
} else {
  log(`  Start it later with: ${c.bold("npm run web")}`);
}
log(`  Health check anytime: ${c.bold("npm run doctor")}\n`);
